// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfpKdsydUvsSnFmw5JM2L7El4EjvwUy-A',
    appId: '1:778677827043:web:360fa1ac1d3b6f80619cd6',
    messagingSenderId: '778677827043',
    projectId: 'boomerang-fec61',
    authDomain: 'boomerang-fec61.firebaseapp.com',
    storageBucket: 'boomerang-fec61.firebasestorage.app',
    measurementId: 'G-7JYMX3QW32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfc96JIPb4TvxSsu_KybLuqYhhUCo9rGw',
    appId: '1:778677827043:android:b4f932125777fd46619cd6',
    messagingSenderId: '778677827043',
    projectId: 'boomerang-fec61',
    storageBucket: 'boomerang-fec61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9liCjizoUljMixTkXG2m1zTA_TaGFkK8',
    appId: '1:778677827043:ios:b58a92e09d32c72b619cd6',
    messagingSenderId: '778677827043',
    projectId: 'boomerang-fec61',
    storageBucket: 'boomerang-fec61.firebasestorage.app',
    iosBundleId: 'com.ayoubhassan.boomerang',
  );
}
